package com.maqsad.ewallet.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "wallet")
public class Wallet {
	@DynamoDBHashKey(attributeName = "walletId")
	@DynamoDBAutoGeneratedKey
	private String walletId;
	@DynamoDBAttribute
	private String userId;
	@DynamoDBAttribute
	private double balance;

	

}
